Repository paketo-buildpacks/sbt, pull requests merged in 2022-08, with the labels that each got.

#162 Update Pipeline to 1.25.2
  .github/pipeline-version
  .github/workflows/pb-create-package.yml
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
  .github/workflows/pb-update-sbt.yml
Labels: type:task, semver:patch

#163 Bump go.mod dependencies
  go.mod
  go.sum
Labels: semver:patch, type:dependency-upgrade

#168 Allow setting a SBT repositories file via an environment variable
  README.md
  buildpack.toml
  sbt/build.go
  sbt/build_test.go
Labels: type:enhancement, semver:minor

#173 Implement RFC 0050: Rename Buildpack
  README.md
  buildpack.toml
Labels: type:task, semver:patch
